
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CadSis457
{

using System;
    using System.Collections.Generic;
    
public partial class Venta
{
        public object transccion;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Venta()
    {

        this.VentaDetalle = new HashSet<VentaDetalle>();

    }


    public int id { get; set; }

    public int idUsuario { get; set; }

    public int idCliente { get; set; }

    public decimal totalVenta { get; set; }

    public System.DateTime fechaVenta { get; set; }

    public string usuarioRegistro { get; set; }

    public System.DateTime fechaRegistro { get; set; }

    public short estado { get; set; }



    public virtual Cliente Cliente { get; set; }

    public virtual Usuario Usuario { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VentaDetalle> VentaDetalle { get; set; }

}

}
